# Generated by Django 5.1.3 on 2025-07-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('sub1', models.FloatField()),
                ('sub2', models.FloatField()),
            ],
        ),
    ]
